INSERT INTO `QUESTION_TYPES`(`ID`, `NAME`) VALUES (1, 'Question-Response');
INSERT INTO `QUESTION_TYPES`(`ID`, `NAME`) VALUES (2, 'Fill_In_The_Blank');
INSERT INTO `QUESTION_TYPES`(`ID`, `NAME`) VALUES (3, 'Multiple_Choice');
INSERT INTO `QUESTION_TYPES`(`ID`, `NAME`) VALUES (4, 'Picture-Response');
INSERT INTO `QUESTION_TYPES`(`ID`, `NAME`) VALUES (5, 'Multi-Answer');
INSERT INTO `QUESTION_TYPES`(`ID`, `NAME`) VALUES (6, 'Muliple_Choice_With_Multiple_Answers');
INSERT INTO `QUESTION_TYPES`(`ID`, `NAME`) VALUES (7, 'Matching');
INSERT INTO `QUESTION_TYPES`(`ID`, `NAME`) VALUES (8, 'Graded');


INSERT INTO `USER_TYPES`(`ID`, `NAME`) VALUES (1, 'USER');
INSERT INTO `USER_TYPES`(`ID`, `NAME`) VALUES (2, 'ADMIN');

INSERT INTO `ACHIEVEMENT_TYPES`(`ID`, `NAME`) VALUES (1, 'Amateur Author');
INSERT INTO `ACHIEVEMENT_TYPES`(`ID`, `NAME`) VALUES (2, 'Prolific Author');
INSERT INTO `ACHIEVEMENT_TYPES`(`ID`, `NAME`) VALUES (3, 'Prodigious Author');
INSERT INTO `ACHIEVEMENT_TYPES`(`ID`, `NAME`) VALUES (4, 'Quiz Machine');
INSERT INTO `ACHIEVEMENT_TYPES`(`ID`, `NAME`) VALUES (5, 'I am the Greatest');
INSERT INTO `ACHIEVEMENT_TYPES`(`ID`, `NAME`) VALUES (6, 'Practice Makes Perfect');
INSERT INTO `ACHIEVEMENT_TYPES`(`ID`, `NAME`) VALUES (7, 'New one');

INSERT INTO `QuizWebsiteDatabase`.`NOTIFICATION_TYPES` (`ID`, `NAME`) VALUES ('1', 'CHALLENGE_REQUEST');
INSERT INTO `QuizWebsiteDatabase`.`NOTIFICATION_TYPES` (`ID`, `NAME`) VALUES ('2', 'FRIEND_REQUEST');
INSERT INTO `QuizWebsiteDatabase`.`NOTIFICATION_TYPES` (`ID`, `NAME`) VALUES ('3', 'GRADE_REQUEST');
INSERT INTO `QuizWebsiteDatabase`.`NOTIFICATION_TYPES` (`ID`, `NAME`) VALUES ('4', 'MESSAGE');
