INSERT INTO `QUESTION_TYPES`(`ID`, `NAME`) VALUES (1, 'Question-Response');
INSERT INTO `QUESTION_TYPES`(`ID`, `NAME`) VALUES (2, 'Fill_In_The_Blank');
INSERT INTO `QUESTION_TYPES`(`ID`, `NAME`) VALUES (3, 'Multiple_Choice');
INSERT INTO `QUESTION_TYPES`(`ID`, `NAME`) VALUES (4, 'Picture-Response');
INSERT INTO `QUESTION_TYPES`(`ID`, `NAME`) VALUES (5, 'Multi-Answer');
INSERT INTO `QUESTION_TYPES`(`ID`, `NAME`) VALUES (6, 'Muliple_Choice_With_Multiple_Answers');
INSERT INTO `QUESTION_TYPES`(`ID`, `NAME`) VALUES (7, 'Matching');

INSERT INTO `USER_TYPES`(`ID`, `NAME`) VALUES (1, 'USER');
INSERT INTO `USER_TYPES`(`ID`, `NAME`) VALUES (2, 'ADMIN');